language: cpp

branches:
    only:
        - testing-docs

sudo: enabled

before_install:
      - sudo apt-get update
      - sudo apt-get install -y doxygen

script:
    - doxygen doxygen.conf

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: testing-docs
    local-dir: documentation
    repo: ISSUIUC/flightcode-docs
    target-branch: master