#pragma once

//#define THREAD_DEBUG
// #define SERIAL_PLOTTING
//#define WAIT_SERIAL

#define ENABLE_ORIENTATION
#define ENABLE_HIGH_G
#define ENABLE_LOW_G
#define ENABLE_GPS
#define ENABLE_GAS
#define ENABLE_BAROMETER
#define ENABLE_MAGNETOMETER
#define ENABLE_SD
#define ENABLE_TELEMETRY
#define ENABLE_BUZZER
