#ifndef BUZZER_CONTROL_H
#define BUZZER_CONTROL_H

#include "dataLog.h"
#include "acShared.h"

/* ======= AUTOGENERATED ======= */

enum BuzzerState {
    INITIAL,
    SPUTNIK_0,
    SPUTNIK_1,
    SPUTNIK_2_0,
    SPUTNIK_2_1,
    SPUTNIK_2_2,
    SPUTNIK_2_3,
    SPUTNIK_2_4,
    SPUTNIK_2_5,
};

unsigned int BuzzerStates[9][3] = {
    /* INITIAL*/ {0, 0, INITIAL},
    /* SPUTNIK 0 */ { 0, 2500, SPUTNIK_1 },
    /* SPUTNIK 1 */ { 200, 1000, SPUTNIK_0 },
    
    /* SPUTNIK_2 0 */ { 49, 1000, SPUTNIK_2_1 },
    /* SPUTNIK_2 1 */ { 0, 500, SPUTNIK_2_2 },
    /* SPUTNIK_2 2 */ { 49, 1000, SPUTNIK_2_3 },
    /* SPUTNIK_2 3 */ { 82, 1000, SPUTNIK_2_4 },
    /* SPUTNIK_2 4 */ { 0, 500, SPUTNIK_2_5 },
    /* SPUTNIK_2 5 */ { 82, 1000, SPUTNIK_2_0 },
};

/* ======= END AUTOGENERATED ======= */

class BuzzerController {
public:
    explicit BuzzerController(pointers *);

    void tickBuzzer();
    void setBuzzerState(BuzzerState state);

private:
    BuzzerState curr_state;
    unsigned long time_since_state_start;

    pointers* rocket_state;
    FSM_State last_rocket_fsm_state;
};


#endif