# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hilsimpacket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12hilsimpacket.proto\"\x82\x03\n\x0cHILSIMPacket\x12\x13\n\x0bimu_high_ax\x18\x01 \x01(\x02\x12\x13\n\x0bimu_high_ay\x18\x02 \x01(\x02\x12\x13\n\x0bimu_high_az\x18\x03 \x01(\x02\x12\x1a\n\x12\x62\x61rometer_altitude\x18\x04 \x01(\x02\x12\x1d\n\x15\x62\x61rometer_temperature\x18\x05 \x01(\x02\x12\x1a\n\x12\x62\x61rometer_pressure\x18\x06 \x01(\x02\x12\x12\n\nimu_low_ax\x18\x07 \x01(\x02\x12\x12\n\nimu_low_ay\x18\x08 \x01(\x02\x12\x12\n\nimu_low_az\x18\t \x01(\x02\x12\x12\n\nimu_low_gx\x18\n \x01(\x02\x12\x12\n\nimu_low_gy\x18\x0b \x01(\x02\x12\x12\n\nimu_low_gz\x18\x0c \x01(\x02\x12\r\n\x05mag_x\x18\r \x01(\x02\x12\r\n\x05mag_y\x18\x0e \x01(\x02\x12\r\n\x05mag_z\x18\x0f \x01(\x02\x12\x11\n\tornt_roll\x18\x10 \x01(\x02\x12\x12\n\nornt_pitch\x18\x11 \x01(\x02\x12\x10\n\x08ornt_yaw\x18\x12 \x01(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hilsimpacket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HILSIMPACKET']._serialized_start=23
  _globals['_HILSIMPACKET']._serialized_end=409
# @@protoc_insertion_point(module_scope)
