name: clang-format Style Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'TARS/src'
            exclude: '(ChRt|SparkFunLSM9DS1|nanopb_generator|hilsimpacket.pb|.proto|Eigen|MS5611|RH|RadioHead|SparkFun_KX13X_Arduino_Library-1.0.7|SparkFun_u-blox_GNSS_Arduino_Library-main)' # Exclude files containing these words
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        fallback-style: 'Google' # optional
