name: clang-format Style Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'flight'
            exclude: '(ChRt|SparkFunLSM9DS1|EigenArduino-Eigen30|eigen-3.4.0)' # Exclude files containing these words
          - check: 'ground'
            exclude: ''
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v3.4.0
      with:
        clang-format-version: '11'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        fallback-style: 'Google' # optional
