name: SILSIM check
on: [push]

jobs:
  silsim:
    name: SILSIM Works
    runs-on: ubuntu-latest
    steps:
      # - name: Install dependencies
      #   run: |
      #     sudo apt install git
      #     sudo apt-get -y install cmake
      # - name: Download SILSIM
      #   run: |    
      #     git clone https://github.com/ISSUIUC/ISS_SILSIM
      # - name: Install and run SILSIM
      #   run: |  
      #     cd ISS_SILSIM
      #     git submodule update --init --recursive
      #     mkdir build
      #     cd build
      #     cmake ..
      #     cd ..
      #     make -C build ISS_SILSIM  
      #     ./build/ISS_SILSIM
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK