name: SILSIM check
on: [push]

jobs:
  silsim:
    name: SILSIM Works
    runs-on: ubuntu-latest
    steps:
      # - name: Install dependencies
      #   run: |
      #     sudo apt install git
      #     sudo apt-get -y install cmake
      # - name: Download SILSIM
      #   run: |    
      #     git clone https://github.com/ISSUIUC/ISS_SILSIM
      # - name: Install and run SILSIM
      #   run: |  
      #     cd ISS_SILSIM
      #     git submodule update --init --recursive
      #     mkdir build
      #     cd build
      #     cmake ..
      #     cd ..
      #     make -C build ISS_SILSIM  
      #     ./build/ISS_SILSIM
      # https://hooks.slack.com/services/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
      - name: Send hello world message
        uses: 8398a7/action-slack@v3
        with:
          status: 'Hello world'
          fields: '{"field1": "value1", "field2": "value2"}'
          text: 'This is a message from Github Actions'
          channel: '#bot-testing'
        env:
          SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'

      
      