name: SILSIM CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: update SILSIM
      run: |
        cd TARS
        git submodule init
        git submodule update
    - name: run SILSIM
      run: |
        cd TARS
        pio run -e mcu_silsim -t upload
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_MESSAGE: 'SILSIM :troll:'
        SLACK_TITLE: 'Silsim Status: ${{ job.status }}'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Checkout
      uses: actions/checkout@v1
    - run: echo "Test file " > test.txt
    - name: Upload log file to slack
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_TOKEN }}
        path: test.txt
        channel: bot-testing

