name: SILSIM check
on: [push]

jobs:
  silsim:
    name: SILSIM Works
    runs-on: ubuntu-latest
    steps:
      # - name: Install dependencies
      #   run: |
      #     sudo apt install git
      #     sudo apt-get -y install cmake
      # - name: Download SILSIM
      #   run: |    
      #     git clone https://github.com/ISSUIUC/ISS_SILSIM
      # - name: Install and run SILSIM
      #   run: |  
      #     cd ISS_SILSIM
      #     git submodule update --init --recursive
      #     mkdir build
      #     cd build
      #     cmake ..
      #     cd ..
      #     make -C build ISS_SILSIM  
      #     ./build/ISS_SILSIM
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'C052ZP64ARM'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: 'xoxb-5118805236916-5118826162228-zUoB4fY1TjoqiWcGMBKFLYv8'
          