name: SILSIM check
on: [push]

jobs:
  silsim:
    name: SILSIM Works
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt install git
          sudo apt-get -y install cmake
      - name: Download SILSIM
        run: |    
          git clone https://github.com/ISSUIUC/ISS_SILSIM
      - name: Install and run SILSIM
        run: |  
          cd ISS_SILSIM
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake ..
          cd ..
          make -C build ISS_SILSIM  
          ./build/ISS_SILSIM
      - name: Send email notification
        if: ${{ always() }}
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          subject: SILSIM Check Status - ${{ job.status }}
          from: SILSIM BOT B)
          to: ${{ steps.get_email.outputs.email }}
          body: |
            The SILSIM check has completed with status ${{ job.status }}.

      - name: Get user email
        id: get_email
        run: |
          curl -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/emails | jq '.[0].email'