name: SILSIM check
on: [push]

jobs:
  silsim:
    name: SILSIM Works
    runs-on: ubuntu-latest
    steps:
      # - name: Install dependencies
      #   run: |
      #     sudo apt install git
      #     sudo apt-get -y install cmake
      # - name: Download SILSIM
      #   run: |    
      #     git clone https://github.com/ISSUIUC/ISS_SILSIM
      # - name: Install and run SILSIM
      #   run: |  
      #     cd ISS_SILSIM
      #     git submodule update --init --recursive
      #     mkdir build
      #     cd build
      #     cmake ..
      #     cd ..
      #     make -C build ISS_SILSIM  
      #     ./build/ISS_SILSIM
      - name: Send hello world message
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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' # required
        if: always() # Pick up events even if the job fails or is canceled.
