name: SILSIM check
on: [push]

jobs:
  silsim:
    name: SILSIM Works
    runs-on: ubuntu-latest
    steps:
      # - name: Install dependencies
      #   run: |
      #     sudo apt install git
      #     sudo apt-get -y install cmake
      # - name: Download SILSIM
      #   run: |    
      #     git clone https://github.com/ISSUIUC/ISS_SILSIM
      # - name: Install and run SILSIM
      #   run: |  
      #     cd ISS_SILSIM
      #     git submodule update --init --recursive
      #     mkdir build
      #     cd build
      #     cmake ..
      #     cd ..
      #     make -C build ISS_SILSIM  
      #     ./build/ISS_SILSIM
      - id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "CHANNEL_ID"
        payload: |
          {
            "text": "Deployment started (In Progress)",
            "attachments": [
              {
                "pretext": "Deployment started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.BOT_KEY}}
      - uses: slackapi/slack-github-action@v1.23.0
        with:
          # Unlike the step posting a new message, this step does not accept a channel name.
          # Please use a channel ID, not a name here.
          channel-id: "C052ZP64ARM"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment finished (Completed)",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.BOT_KEY}}
